site: Alexander Paar

collections:
  pages:
    output: true
    permalink: /:name
  events:
    output: true
    permalink: /events/:slug
  projects:
    output: true
    permalink: /project/:slug
  research:
    output: true
    permalink: /research/:slug
  about:
    output: true
    permalink: /about/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "research"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "about"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  